---
title: "Week 13"
author: "Soh Li Ying"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  latex_engine: pdflatex
  keep_tex: true
  word_wrap: true
  extra_dependencies: ["geometry"]
---

# Week 9

## Finalised Topic 
Title: Exploring the Psychological impact of Social Media
To come up with a data story relating social media and its negative impact on its users in various different ways, such as an evoked sense of stress, negative comments, cyber bullying, and social media addiction - all of which leading to detrimental effects on the mental health. 

## Curated datasets
* "https://www.kaggle.com/datasets/ruchi798/stress-analysis-in-social-media\n"
* "https://www.kaggle.com/datasets/souvikahmed071/social-media-and-mental-health\n"
* "https://www.kaggle.com/datasets/subhajeetdas/hate-comment\n"
* "https://www.kaggle.com/datasets/mohammadalazawi/social-media-addiction\n"
* "https://www.kaggle.com/datasets/saurabhshahane/cyberbullying-dataset\n"

## Webpage link
"https://liyinnng.github.io/"
https://liyinnng.github.io/school_projects/NM2207-datastory/data-story.html (for the datastory specifically)

# Week 10

## (1) Question to answer 
What are the relationships between social media usage and its negative impacts?

## (2) Why is this an important qn?
As social media usage continues to expand globally, there is a growing worry about its impact on the mental and overall health of individuals and communities. A survey conducted by the [Cybersmile Foundation](https://www.marketingtechnews.net/news/2022/jun/22/89-of-people-feel-social-media-negatively-affects-their-mental-health/) reveals that a significant 89% of social media users perceive social media as harmful to their mental well-being. [According Ms Ranjini Veerappan](https://www.channelnewsasia.com/singapore/big-read-teenagers-social-media-addiction-cost-mental-health-3647121), a certified addiction specialist at Holistic Psychotherapy Centre, a child's brain is still maturing and rapidly developing until they are about 25 years old. This leads to the prevalence of negative effects of social media within youths. Research by the [National    Center for Health Research](https://www.center4research.org/social-media-affects-mental-health/) has also conducted a study on adolescents has identified that body image, for girls and boys, is harmed by social media use.

## (3) Row and columns of dataset used: 
1. What is your age?
2. Gender
6. Do you use social media?
- "Yes"/"No" data --> str type, which makes it difficult to use it in computations. Hence i changed them to 1/0, where 1 represents yes, and 0 represents no. 
- before processing the rest of the data for comparison, remove those with '0' whenever required (eg: when comparing between people who use social media)
8. What is the average time you spend on social media every day?
10. How often do you get distracted by Social media when you are busy doing something?
12. On a scale of 1 to 5, how easily distracted are you?
13. On a scale of 1 to 5, how much are you bothered by worries?
14. Do you find it difficult to concentrate on things?
15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?
16. Following the previous question, how do you feel about these comparisons, generally speaking?
17. How often do you look to seek validation from features of social media?
18. How often do you feel depressed or down?
20. On a scale of 1 to 5, how often do you face issues regarding sleep?

# Week 12
## Challenges and errors faced: 

The first challenge I faced was in my shiny app that was used to create an interactive violin graph. The y-axis of my graphs when I first launched my shiny app were messed up since they followed the coloumn names of data sets (Eg: "X20..On.a.scale.of.1.to.5..how.often.do.you.face.issues.regarding.sleep."). I managed to customize and change the names of the y-axis after I found that you could change the names of the y-axis when you include a title <- "(y-axis name)" instead on changing the y-label since the y-label is used to identify the column used for the y-axis.  

The second challenge I faced was also in my other shiny app. First, I struggled with separating the genders under the same column of "gender" as I wanted to separate them for further analysis of my data set. After scouraging the web for examples of other shiny apps that have done the same (it was difficult since most of the datasets already had the columns they wanted to compare in different columns already), I finally managed to find one and referenced the code. So how I did it was through utilising multiple if-return and else-return functions. I also wanted to include 2 bar graphs both in the main panel, and solved the issue through specifying 2 different plotOutput in the mainpanel() under the UI section, and then later bind the codes of the bar graphs to each of them respectively. 

The third difficulty I faced was deciding on the type of visualisation to use for the data analysis for the relationship between 2 of my columns, "How often do you seek validation from social media?" and "How often do you feel depressed or down?" becuase both of the data in the columns are numbers from 1-5, indicated by surveyors of their perception towards the questions. The first visualisations that would come to mind would be bar graphs, line graphs, etc... However, those will not work in showing a direct relationship between both columns. And I went to search on the website on data visualisation ways to illustrate relationships between 2 variables and found out that a heat map would be ideal in doing so. So I went online to find out more about how I can include a heat map in my quarto docs, and managed to successfully incorporate it in my data analysis. 

# Final Submission

Title: Unveiling the Dark Side of Social Media: A Comprehensive Data Exploration

(1) **Theme of the Data Story:**
In an era dominated by the ubiquitous presence of social media, the theme of this data story centres around the investigation of its negative and detrimental impacts on individuals and communities. The focus extends beyond casual speculation, delving into empirical evidence to unravel the intricate web of consequences associated with the escalating use of social platforms.

(2) **Importance of Addressing the Question:**
The pervasive nature of social media usage demands an examination of its consequences. The sheer scale of its influence, especially on the mental health of individuals, has raised considerable concerns. A survey by the Cybersmile Foundation underscores the gravity of the situation, revealing that a staggering 89% of social media users perceive it as harmful to their mental well-being. The importance of addressing this question lies in the need to comprehend the multifaceted impact of social media on mental health and overall well-being, particularly among the youth. Ranjini Veerappan, a certified addiction specialist, highlights the vulnerability of a developing brain, making it imperative to scrutinize the negative effects of social media on the younger demographic.

(3) **Relevance of Curated Data Sources:**
The chosen data sources play a pivotal role in substantiating the narrative on the negative impacts of social media. The first dataset, derived from survey responses, serves as a valuable repository of insights into the subjective experiences of individuals. It encapsulates their concerns and perceptions regarding the impact of social media on their mental health. This qualitative data complements the quantitative aspects, offering a holistic view of the user experience.

The second dataset, a word cloud illustrating prevalent themes in hateful comments, provides a stark illustration of the darker side of online interactions. It sheds light on the words that are most commonly used in hateful comments, emphasizing the need for responsible and empathetic engagement on social platforms.

(4) **Insights from the Data and Depiction in Plots:**
The exploration of the negative impacts of social media unfolds through a series of insightful visualizations and analyses.

- **Donut, Bar and Pie charts:** We start off with understanding the basic demographics of our dataset, such as the age group distribution, proportion of social media users, and the average time spent on social media. 

- **Shiny Heatmaps:** The heatmaps hosted on shiny unveils negative relationships between social media usage and critical facets of well-being (sleep-quality, concentration, and general worries). The progressive darkening of the heatmap along the y-axis illustrate the escalating impact of social media on these variables.

- **Validation-Seeking and Depression:** A subsequent heatmap probes the relationship between seeking validation on social media and the frequency of feeling depressed. The analysis reveals that those who seek validation frequently are more prone to experiencing depressive feelings. This insight underscores the psychological toll that the quest for online validation can take on individuals.

- **Age-Based Analysis:** Moving on to our next shiny app, we investigate Frequency in comparing oneself to other successful people through the use of social media, and how one feels about these comparisons generally speaking with a line and area chart. I wanted to focus on how the user's age affects the impact of social media usage on one. By categorizing respondents into different age brackets, the analysis emphasizes the vulnerability of younger users to negative impacts caused by comparisons on social media.

- **Word Cloud Analysis:** The interactive word cloud illustrating the most commonly used words in hateful comments provides a qualitative dimension to the exploration. It highlights prevalent themes related to gender, race, and religion, offering a reminder of the need to foster a healthier online discourse.

While these are very brief insights and observations from our data set, I have conducted deeper analysis and observations on my website, alongside concrete research that supports the insights. 

(5) **Implementation of the Project:**
The implementation of this project reflects a comprehensive approach to data storytelling.

- **Interactive Charts with echart4r:** While searching for visual charts that could better illustrate my data story, I chanced upon the echart4r package, which allows for creation of dynamic and interactive charts to enhance the storytelling aspect of data representation. Although the argument names to call for functions are widely different from ggplot2, the data processing and thought process behind passing relevant variable through the arguments are similar to what we have learned during class. 

- **Quarto for Webpage Development:** Upon reading through the various functions Quarto provides for webpage development, I experimented and managed to incorporate some interactive aspects, such as PowerPoint slides (with reveal.js) and panels. This allowed for a more structured and layered presentation of the data.

- **SCSS for Customization:** I also went on to explore the difference between using CSS and SCSS, which allows flexible customization that is not achievable with built-in themes. I proceeded with SCSS as it allows greater flexibility than CSS. This customization extended to specific aspects of the website, such as font size and colour schemes, contributing to a visually appealing and cohesive presentation.

**Conclusion:**
In conclusion, it has really been an exciting journey while creating this data story, that offers a nuanced exploration of the negative impacts of social media. By weaving together insights from user perceptions, interactive visualizations, and analyses of online interactions, the narrative sheds light on the multifaceted consequences of social media usage to allow us to better foster a digital environment that promotes positive engagement and safeguards the well-being of its users.

**References & Citations:**

- Ahmed, S., &amp; Syeda, M. N. (2023, July). Social Media and Mental Health. https://www.kaggle.com/datasets/souvikahmed071/social-media-and-mental-health/data. 

- Baptist Health. (2020, November 6). How social media affects attention span. https://www.baptisthealth.com/blog/family-health/how-social-media-affects-attention-span#:~:text=Not%20only%20are%20attention%20spans,decreased%20attention%20on%20each%20task. 

- Cramer, S., &amp; Inkster, B. (2017, May). #StatusOfMind Social media and young people’s mental health and wellbeing. https://www.rsph.org.uk/our-work/campaigns/status-of-mind.html

- Das, S. (2022, November 1). Social media hate comments. Kaggle. https://www.kaggle.com/datasets/subhajeetdas/hate-comment 

- Dean, B. (2023, November 15). How many people use Social Media in 2023? (65+ statistics). Backlinko. https://backlinko.com/social-media-users#social-media-usage-stats 

- Lau, D. (2023, July 24). The big read: Teenagers hooked on social media - what’s the cost to their mental health? CNA. https://www.channelnewsasia.com/singapore/big-read-teenagers-social-media-addiction-cost-mental-health-3647121 

- MacRae, D. (2022, June 22). 89% of people feel social media negatively affects their mental health. Marketing Tech News. https://www.marketingtechnews.net/news/2022/jun/22/89-of-people-feel-social-media-negatively-affects-their-mental-health/ 

- Mir, E., &amp; Sun, A. (2023, July 20). Social Media and adolescents’ and Young Adults’ mental health. National Center for Health Research. https://www.center4research.org/social-media-affects-mental-health/ 

- Newport Academy. (2023, August 3). The theory of social comparison and Mental Health. https://www.newportacademy.com/resources/empowering-teens/theory-of-social-comparison/ 

- Nuno, S. (2023, February 14). How does social media affect sleep? (2023). Mattress Clarity. https://www.mattressclarity.com/sleep-resources/social-media-affects-sleep/#:~:text=Social%20Media%20and%20Insomnia,understanding%20of%20when%20bedtime%20is. 

- Robinson, L., &amp;  Smith, M. (2023, March 29). Social Media and Mental Health. HelpGuide.org. https://www.helpguide.org/articles/mental-health/social-media-and-mental-health.htm#:~:text=using%20social%20media.-,Modifying%20social%20media%20use%20to%20improve%20mental%20health%20step%201,%2C%20sleep%20problems%2C%20and%20FOMO. 

